SOS_VEC_POS = 95
EOS_VEC_POS = 96
UNKNOWN_CHAR_VEC_POS = 97

REVIEW_BATCH_SIZE = 1
MAX_GENERATE_LEN = 1000

ONE_HOT_BEER_STYLE_VECTOR_LEN = 104
ONE_HOT_RATING_VECTOR_LEN = 5
ONE_HOT_CHAR_VECTOR_LEN = 98
BIAS_VECTOR_LEN = 1

ONE_HOT_VECTOR_LEN = (ONE_HOT_BEER_STYLE_VECTOR_LEN +
                      BIAS_VECTOR_LEN +
                      ONE_HOT_RATING_VECTOR_LEN +
                      ONE_HOT_CHAR_VECTOR_LEN)
CHAR_START_IDX = (ONE_HOT_BEER_STYLE_VECTOR_LEN +
                  ONE_HOT_RATING_VECTOR_LEN +
                  BIAS_VECTOR_LEN)
